name: widgetbook_workspace
description: 'Form&Fun Flutter Test - Widgetbook Workspace'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  design_system:
    path: ../design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.20.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/
